[project]
name = "amadeus-amth"
version = "0.1.0"
description = "Amadeus - a self-hosted AI assistant with an autonomous file workspace"
readme = "README.md"
authors = [
    { name = "AaronMathew026", email = "aaronmathew026@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "ollama>=0.6.2",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
amadeus-amth = "amadeus_amth:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
